### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ElJoelReis** [notisrac/SoftEtherAdmin#1]
Hello Guys,
i installed all the things, but when i star pm2 or do a node app.js gives me this.

```
root@static-38-28-134-91:/srv/SoftEtherAdmin# node app.js
/srv/SoftEtherAdmin/modules/softEther.js:120
    executeFile: function (fileName, hub = null, settings = {}) {
                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/SoftEtherAdmin/routes/server.js:3:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by ElJoelReis** [comment]
Problem with node version. Solved
